### ISSUE TITLE
Webview too long

### ISSUE THREAD

**Issue by brian-silverman** [scottsilverlabs/raspberrystem-ide#42]
webview window appear too long by exactly 2em (likely not coincedentally the same as height of titlebar).  You can tell this because 1) some pages can't scroll all the way to the bottom, and 2) the scrollbar scrolls down an extra bit past the bottom of the screen.

Note: this may not be an issue once #39 is fixed.

**Comment by Slowki** [comment]
Fixed when I implemented #39.
