### ISSUE TITLE
Rotating gif

### ISSUE THREAD

**Issue by brian-silverman** [scottsilverlabs/raspberrystem-ide#61]
Modify rotating gif to better images (16?).  Also, static gif (non-rotating) is slightly misaligned from animated gif.

**Comment by Slowki** [comment]
Fixed the alignment, but GIFs are limited to a custom defined 8 bit color table, I tweaked the colors in the table a bit, but that's about as good as it gets quality-wise. The quality difference between the rotating and non-rotating images is because the non-rotating one is a 32 bit PNG.

**Comment by brian-silverman** [comment]
Gotcha.  I'll take a look at it this week.

**Comment by brian-silverman** [comment]
Looks good.  Case closed!
